export const PERMISSIONS = {
  FAVORITE_CREATE: 'favorite.create',
  FAVORITE_READ: 'favorite.read',
  FAVORITE_DELETE: 'favorite.delete',
  CART_CREATE: 'cart.create',
  CART_READ: 'cart.read',
  CART_DELETE: 'cart.delete',
  REVIEW_CREATE: 'review.create',
  REVIEW_READ: 'review.read',
  REVIEW_UPDATE: 'review.update',
  REVIEW_DELETE: 'review.delete',
  COMMENT_CREATE: 'comment.create',
  COMMENT_READ: 'comment.read',
  COMMENT_UPDATE: 'comment.update',
  COMMENT_DELETE: 'comment.delete',
  OFFER_CREATE: 'offer.create',
  OFFER_READ: 'offer.read',
  OFFER_COUNTER: 'offer.counter',
} as const
